# Generated by Django 5.1.7 on 2025-03-30 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('dead', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'Pollopt')], max_length=10)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('descendants', models.IntegerField(blank=True, default=0)),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, default='https://news.ycombinator.com/')),
                ('text', models.TextField(blank=True, default='')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ('-time', '-score'),
                'permissions': [('can_edit', 'can edit a story')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('dead', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'Pollopt')], max_length=10)),
                ('text', models.TextField(default='')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('descendants', models.IntegerField(blank=True, default=0)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ManyToManyField(blank=True, related_name='replies', to='story.comment')),
                ('story', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='story.story')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ('-time', '-score'),
                'permissions': [('can_edit', 'can edit a comment')],
                'abstract': False,
            },
        ),
    ]
