# Generated by Django 5.1.7 on 2025-04-13 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='story.story'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['type'], name='comments_type_e577ea_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['title'], name='story_title_idx'),
        ),
    ]
