name: zen-hn

services:
  zen-web:
    build:
      context: ./zen_web
      dockerfile: Dockerfile
    env_file:
      - ./zen_web/.env
    environment:
      POSTGRES_DB_HOST: zen-db
      REDIS_HOST: zen-redis
      CACHE_ENGINE: redis
      EMAIL_BACKEND: user_account.email_backend.CeleryEmailBackend
      RUN_MIGRATIONS: 0
      RUN_COLLECTSTATIC: 1
      DEBUG: 0
    command: gunicorn zen_hn.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_files:/home/super_hacker/zen_hn/staticfiles
      - media_files:/home/super_hacker/zen_hn/media
    expose:
      - 8000
    depends_on:
      - zen-db
      - zen-redis
    container_name: zen-web

  zen-db:
    image: postgres
    env_file:
      - ./zen_web/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: zen-db
    restart: always
    ports:
      - "5432:5432"

  zen-celery:
    build:
      context: ./zen_web
    env_file:
      - ./zen_web/.env
    environment:
      REDIS_HOST: redis
    command: python -m celery -A zen_hn worker --loglevel=info
    depends_on:
      - zen-web
      - zen-redis
    container_name: zen-celery
    restart: always

  zen-redis:
    image: redis:alpine
    container_name: zen-redis
    volumes:
      - redis_data:/data
    restart: always

  zen-nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./zen_nginx/default.conf:/etc/nginx/nginx.conf
      - static_files:/home/super_hacker/zen_hn/staticfiles
      - media_files:/home/super_hacker/zen_hn/media
    depends_on:
      - zen-web
    container_name: zen-nginx

volumes:
  static_files:
    name: static_files
  media_files:
    name: media_files
  db_data:
    name: db_data
  redis_data:
    name: redis_data
