name: zen-hn

services:
  zen-web:
    build:
      context: ./zen_web
      dockerfile: Dockerfile_dev
    env_file:
      - ./zen_web/.env
    environment:
      POSTGRES_DB_HOST: zen-db
      REDIS_HOST: zen-redis
      CACHE_ENGINE: redis
      EMAIL_BACKEND: user_account.email_backend.CeleryEmailBackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./zen_web:/home/super_hacker/zen_hn
    ports:
      - "8000:8000"
    depends_on:
      - zen-db
      - zen-redis
    container_name: zen-web

  zen-db:
    image: postgres
    env_file:
      - ./zen_web/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: zen-db
    restart: always
    ports:
      - "5432:5432"

  zen-celery:
    build:
      context: ./zen_web
    env_file:
      - ./zen_web/.env
    environment:
      REDIS_HOST: redis
    command: python -m celery -A zen_hn worker --loglevel=info
    depends_on:
      - zen-web
      - zen-redis
    container_name: zen-celery
    restart: always

  zen-redis:
    image: redis:alpine
    container_name: zen-redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  db_data:
    name: db_data
  redis_data:
    name: redis_data
