FROM python:3.13.3-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/zen_hn

RUN apt-get update && apt-get install -y --no-install-recommends netcat-traditional

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

RUN chmod u+x /usr/src/zen_hn/scripts/entrypoint.dev.sh

ENTRYPOINT ["/usr/src/zen_hn/scripts/entrypoint.dev.sh"]
