# Generated by Django 5.1.7 on 2025-04-13 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['type'], name='polls_type_b63579_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['type'], name='polloptions_type_8b5afe_idx'),
        ),
    ]
